POST http://localhost:5000/api/projects
Content-Type: application/json

{
  "slug": "test-residence",
  "title": "Test Residence",
  "location": "Tunis, Tunisia",
  "status": "available",
  "price": "From 250,000 TND",
  "apartments": 10,
  "deliveryDate": "December 2027",
  "coverImage": "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde",
  "description": "My first project created through the backend API.",
  "mapEmbedUrl": "https://maps.app.goo.gl/BnNaShqw1VeAsoeF7",
  "projectImages": [],
  "apartmentUnits": []
}

###

DELETE http://localhost:5000/api/projects/test-residence

### UPDATE project
PUT http://localhost:5000/api/projects/green-city
Content-Type: application/json

{
  "title": "Green City Updated",
  "location": "Nasr, Tunisia",
  "status": "available",
  "price": "From 650,000 TND",
  "apartments": 24,
  "deliveryDate": "December 2026",
  "coverImage": "https://scontent.ftun14-1.fna.fbcdn.net/v/t39.30808-6/653706179_1525402872926842_416741111423504952_n.jpg",
  "description": "Updated project description.",
  "mapEmbedUrl": "https://www.google.com/maps?q=Sousse,Tunisia&output=embed",
  "projectImages": [],
  "apartmentUnits": []
}

### ADMIN LOGIN

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "YOUR_ADMIN_PASSWORD"
}

###

### ADMIN LOGIN

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "walid",
  "password": "youssef2912"
}

###

POST http://localhost:5000/api/projects
Content-Type: application/json
Authorization: Bearer

{
  "slug": "BAD SLUG !!!",
  "title": "",
  "location": "Tunis",
  "status": "hello",
  "price": "100 TND",
  "apartments": -20,
  "deliveryDate": "",
  "coverImage": "",
  "description": "",
  "mapEmbedUrl": "",
  "projectImages": [],
  "apartmentUnits": []
}

### TEST CONTACT FORM

POST http://localhost:5000/api/contact
Content-Type: application/json

{
  "name": "Youssef",
  "email": "youssef@example.com",
  "phone": "+216 12345678",
  "subject": "Interested in Green City",
  "message": "Hello, I would like to get more information about this project."
}

### GET CONTACT MESSAGES

GET http://localhost:5000/api/contact
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoxLCJ1c2VybmFtZSI6IndhbGlkIiwiaWF0IjoxNzg5ODUzMDgzLCJleHAiOjE3ODk4NjAyODN9.34oz1UtPaEBrfc7CsM19uIkZdz5icEJJfaH_GTWWqpc

### MARK MESSAGE AS READ

PATCH http://localhost:5000/api/contact/1/read
Authorization: Bearer YOUR_ADMIN_TOKEN

### DELETE MESSAGE

DELETE http://localhost:5000/api/contact/1
Authorization: Bearer YOUR_ADMIN_TOKEN